### ISSUE TITLE
[Help] OBD OEM Parameters

### ISSUE THREAD

**Issue by CarlosBelloErla** [goncalo-oliveira/channels#35]
Hi Goncalo,

I Try to use your Teltonika Library for read params of devices. I have two type of devices (FMC920 and FMC003). In both i can read GPS data and some IOElements but into FMC003 i can't read OBD data and i don´t know why.

I try to use Codec8 and codec8 extended but nothing.

[(https://wiki.teltonika-gps.com/view/FMC003)]

`    public class MyDataHandler : ChannelHandler<IAvlData[]>
    {
        private readonly InfluxDbMeasurements _influxDbMeasurements;

        public MyDataHandler(InfluxDbMeasurements influxDbMeasurements)
        {
            _influxDbMeasurements = influxDbMeasurements;
        }
        public override Task ExecuteAsync(IChannelContext context, IAvlData[] data)
        {
            int i = 0;
            string imei = context.Channel.Data["imei"];
          
            foreach (IAvlData vlData in data)
            {
                //HelperClass.ExportToJson(vlData, i);
                _influxDbMeasurements.InsertMeasurements(data, context.Channel.Data["imei"]).GetAwaiter().GetResult();
            }
            return Task.CompletedTask;
        }
    }`

**Comment by goncalo-oliveira** [comment]
Hi there!

OBD data is sent in the `IAvlData.IOData.Elements` array. FMC003, if I'm not mistaken, supports only OBD OEM, so you need to check the element id to know what data you are receiving. You can check the ODB element id in [Teltonika's documentation](https://wiki.teltonika-gps.com/view/FMC003_Teltonika_Data_Sending_Parameters_ID#OBD_OEM_elements). If the OBD data is not being received, you should check the device's configuration. It might be worth checking if the vehicle where the device is plugged in is [supported by the device](https://wiki.teltonika-gps.com/view/OBD_supported_vehicle_list).

Also, I can see that you are writing the `IAvlData` array to the database. I do recommend writing an Adapter to convert the `IAvlData` to a custom object that fits your database schema. Then change your handler to handle the custom object instead. This way, you'll be more protected from changes in the library.

Let me know if you need further help.

**Comment by CarlosBelloErla** [comment]
Thanks for your quick answer!

I attach a Json file with dump data and image files. OBD read parametters but i can't see into JSON File

`        public static void ExportToJson(IAvlData data, int i)
        {
            string filePath = "C:\\Users\\xxxx\\Downloads\\JSON\\teltonikaJson_"+i+".json";
            // Define las opciones de serialización JSON para un formato legible
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            // Serializa el arreglo data a JSON
            string jsonData = JsonSerializer.Serialize(data, options);

            // Escribe el JSON serializado a un archivo
            File.WriteAllText(filePath, jsonData);
        }`

![image](https://github.com/goncalo-oliveira/channels/assets/106149989/d836e6b4-d1fb-4ff3-849e-2b96fe26f40d)

![image](https://github.com/goncalo-oliveira/channels/assets/106149989/cfa2d7ad-5be7-46ad-86b6-77be99f6be82)


[teltonikaJson_0.json](https://github.com/goncalo-oliveira/channels/files/14864598/teltonikaJson_0.json)

**Comment by goncalo-oliveira** [comment]
Indeed there aren't any OBD OEM elements in the JSON you provided. Though, I don't think this has anything to do with the protocol or the library.

Did you check if the vehicle where you plugged the device into is supported? I'm assuming it IS plugged into a real vehicle. 
If the vehicle is in the list, I would advise you to contact Teltonika's support to guide you through the device's configuration and/or firmware update.

**Comment by goncalo-oliveira** [comment]
Sure. You can find details on how to implement an adapter in the [docs](https://channels.docs.faactory.io/channels/adapters/). Since the library forwards `IAvlData[]` in the pipeline, you should adapt from that instead of `IAvlData` to ensure [sequence order](https://channels.docs.faactory.io/channels/middleware/#type-mutation-and-sequence-order) is maintained.

```csharp
public class TelemetryAdapter : ChannelAdapter<IAvlData[]>, IInputChannelAdapter
{
    public override Task ExecuteAsync( IAdapterContext context, IAvlData[] data )
    {
        // adapt/transform data
        var list = new List<MyOwnData>();

        foreach ( var avl in data )
        {
            // ... list.Add( new MyOwnData { ... } );
        }

        // forward adapted data
        context.Forward( list.ToArray() );
    }
}
```

Then your handler can handle `MyOwnData[]` instead of `IAvlData[]`.

```csharp
public class MyDataHandler : ChannelHandler<MyOwnData[]>
{
    public override Task ExecuteAsync( IChannelContext context, MyOwnData[] data )
    {
        // ...
    }
}
```

You then need to adjust the pipeline to use your adapter and handler.

```csharp
services.AddChannels( channel =>
{
    // ...

    channel.AddTeltonikaInputAdapters()
        .AddInputAdapter<TelemetryAdapter>(); // the order is important

    channel.AddInputHandler<MyDataHandler>()

} );
```

You can find more examples of adapters and handlers in the repository [examples](https://github.com/goncalo-oliveira/channels/tree/main/examples).

Let me know how it goes with Teltonika. Good luck!

**Comment by goncalo-oliveira** [comment]
Closing this issue for now as it doesn't seem to be related to the library. Please let me know if this changes.
